name: CI

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      with:
        node-version: '14'
  ##################################
  ##################################

      - name: Node Version
        run: node -v
      - name: Install de dependencias
        run: yarn install
      - name: Roda o Linter!
        run: yarn lint
